### ISSUE TITLE
Regression in emqx_auth_http behavior after upgrade to EMQX 5.x — HTTP Auth endpoints no longer triggered

### ISSUE THREAD

**Issue by criptocoko** [emqx/emqx-docker#78]
## Description

After upgrading from EMQX 4.4.x to EMQX 5.x, our custom HTTP authorization plugin (emqx_auth_http) no longer works. Specifically, the configured endpoints for auth, superuser, and ACL are never triggered. This setup worked perfectly in 4.4, but in 5.x, clients are allowed to connect and subscribe/publish without any authorization — essentially bypassing the plugin entirely.

## Expected Behavior

The plugin should:
- Forward authentication, superuser, and ACL checks to our configured HTTP endpoints.
- Deny connections or actions when the HTTP backend returns a non-authorized response.

## Actual Behavior

In EMQX 5.x:
- The configured HTTP endpoints are never called (verified by inspecting backend logs).
- All clients are granted access, regardless of credentials.
- This is a critical regression in security behavior compared to 4.4.

## Environment

- Dockerized setup
- Base image: emqx/emqx:latest
- Plugin: emqx_auth_http
- Dockerfile symlinks custom emqx_auth_http.conf into /opt/emqx/etc/plugins/
- See configuration snippets below

### docker-compose.yml

```yaml
emqx:
  build:
    context: ./
    dockerfile: ../mirigi-base3/Dockerfile
    target: emqx
  volumes:
    - ../../:/mirigi/apps/shine/
  ports:
    - 18083:18083
    - '5369:5369'
    - '8083:8083'
    - '8084:8084'
    - '4370:4370'
  environment:
    - "EMQX_NAME=emq"
    - "EMQX_HOST=127.0.0.1"
    - "EMQX_ALLOW_ANONYMOUS=true"
    - "EMQX_NOMATCH=deny"
    - "TZ=Etc/UTC"
    - "EMQX_LOADED_PLUGINS=emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_http"
```
### emqx_auth_http.conf

```python
auth.http.auth_req.headers.content-type = application/x-www-form-urlencoded
auth.http.auth_req.url = http://ws.local.com/auth_mqtt/auth
auth.http.auth_req.method = post
auth.http.auth_req.params = clientid=%c,username=%u,password=%P

auth.http.super_req.headers.content-type = application/x-www-form-urlencoded
auth.http.super_req.url = http://ws.local.com/auth_mqtt/superuser
auth.http.super_req.method = post
auth.http.super_req.params = clientid=%c,username=%u

auth.http.acl_req.headers.content-type = application/x-www-form-urlencoded
auth.http.acl_req.url = http://ws.local.com/auth_mqtt/acl
auth.http.acl_req.method = get
auth.http.acl_req.params = access=%A,username=%u,clientid=%c,ipaddr=%a,topic=%t
```

### Dockerfile 

```Dockerfile
FROM emqx/emqx:latest as emqx

USER root

RUN rm -f /opt/emqx/etc/plugins/emqx_auth_http.conf && \
    mkdir -p /opt/emqx/etc/plugins/ && \
    ln -s /mirigi/apps/shine/conf/emqx/plugins/emqx_auth_http.conf /opt/emqx/etc/plugins/emqx_auth_http.conf

```

## Notes
The plugin is correctly symlinked via Dockerfile into the expected directory.

No errors are shown in EMQX logs, but no HTTP requests are made.

**The plugin is NOT listed in the loaded plugins.**

## Request
Please confirm if emqx_auth_http is supported in EMQX 5.x.

If so, is there a breaking change in how plugins are loaded or configured?

If not, what's the recommended path to achieve the same functionality?
